import unittest
from Chatbot.extractors.color.core.tokenizer import tokenize_text

class TestTokenizeText(unittest.TestCase):
    def test_case_01(self): self.assertEqual(dict(tokenize_text('')[1]), {})
    def test_case_02(self): self.assertEqual(dict(tokenize_text('blue')[1]), {'blue': 1})
    def test_case_03(self): self.assertEqual(dict(tokenize_text('Blue')[1]), {'blue': 1})
    def test_case_04(self): self.assertEqual(dict(tokenize_text('blue blue')[1]), {'blue': 2})
    def test_case_05(self): self.assertEqual(dict(tokenize_text('red, blue')[1]), {'red': 1, ',': 1, 'blue': 1})
    def test_case_06(self): self.assertEqual(dict(tokenize_text('soft pink')[1]), {'soft': 1, 'pink': 1})
    def test_case_07(self): self.assertEqual(dict(tokenize_text('Soft Pink')[1]), {'soft': 1, 'pink': 1})
    def test_case_08(self): self.assertEqual(dict(tokenize_text('soft pink pink')[1]), {'soft': 1, 'pink': 2})
    def test_case_09(self): self.assertEqual(dict(tokenize_text('soft, pink, soft')[1]), {'soft': 2, ',': 2, 'pink': 1})
    def test_case_10(self): self.assertEqual(dict(tokenize_text('I love soft pink shades')[1]), {'i': 1, 'love': 1, 'soft': 1, 'pink': 1, 'shades': 1})
    def test_case_11(self): self.assertEqual(dict(tokenize_text('shiny and elegant')[1]), {'shiny': 1, 'and': 1, 'elegant': 1})
    def test_case_12(self): self.assertEqual(dict(tokenize_text('glowy glowy glowy')[1]), {'glowy': 3})
    def test_case_13(self): self.assertEqual(dict(tokenize_text('bright red and dark blue')[1]), {'bright': 1, 'red': 1, 'and': 1, 'dark': 1, 'blue': 1})
    def test_case_14(self): self.assertEqual(dict(tokenize_text('Peachy, dusty rose')[1]), {'peachy': 1, ',': 1, 'dusty': 1, 'rose': 1})
    def test_case_15(self): self.assertEqual(dict(tokenize_text('red! blue? green.')[1]), {'red': 1, '!': 1, 'blue': 1, '?': 1, 'green': 1, '.': 1})
    def test_case_16(self): self.assertEqual(dict(tokenize_text('Light-Pink is nice')[1]), {'light': 1, '-': 1, 'pink': 1, 'is': 1, 'nice': 1})
    def test_case_17(self): self.assertEqual(dict(tokenize_text('bold, vibrant, edgy')[1]), {'bold': 1, ',': 2, 'vibrant': 1, 'edgy': 1})
    def test_case_18(self): self.assertEqual(dict(tokenize_text('natural shades please')[1]), {'natural': 1, 'shades': 1, 'please': 1})
    def test_case_19(self): self.assertEqual(dict(tokenize_text('No shiny or bold')[1]), {'no': 1, 'shiny': 1, 'or': 1, 'bold': 1})
    def test_case_20(self): self.assertEqual(dict(tokenize_text("I don't like red")[1]), {'i': 1, 'do': 1, "n't": 1, 'like': 1, 'red': 1})
    def test_case_21(self): self.assertEqual(dict(tokenize_text('Nothing too shiny')[1]), {'nothing': 1, 'too': 1, 'shiny': 1})
    def test_case_22(self): self.assertEqual(dict(tokenize_text('very very shiny')[1]), {'very': 2, 'shiny': 1})
    def test_case_23(self): self.assertEqual(dict(tokenize_text('dark pink blush and lipstick')[1]), {'dark': 1, 'pink': 1, 'blush': 1, 'and': 1, 'lipstick': 1})
    def test_case_24(self): self.assertEqual(dict(tokenize_text('elegant formal timeless')[1]), {'elegant': 1, 'formal': 1, 'timeless': 1})
    def test_case_25(self): self.assertEqual(dict(tokenize_text('Red red red red red')[1]), {'red': 5})
    def test_case_26(self): self.assertEqual(dict(tokenize_text('Soft. Clean. Minimal.')[1]), {'soft': 1, '.': 3, 'clean': 1, 'minimal': 1})
    def test_case_27(self): self.assertEqual(dict(tokenize_text('a b c d e f g h i j')[1]), {'a': 1, 'b': 1, 'c': 1, 'd': 1, 'e': 1, 'f': 1, 'g': 1, 'h': 1, 'i': 1, 'j': 1})
    def test_case_28(self): self.assertEqual(dict(tokenize_text('rosewood')[1]), {'rosewood': 1})
    def test_case_29(self): self.assertEqual(dict(tokenize_text('barely-there skin-like no makeup')[1]), {'barely': 1, '-': 2, 'there': 1, 'skin': 1, 'like': 1, 'no': 1, 'makeup': 1})
    def test_case_30(self): self.assertEqual(dict(tokenize_text('moody vibes')[1]), {'moody': 1, 'vibes': 1})
    def test_case_31(self): self.assertEqual(dict(tokenize_text('I want something fun, playful, but elegant')[1]), {'i': 1, 'want': 1, 'something': 1, 'fun': 1, ',': 2, 'playful': 1, 'but': 1, 'elegant': 1})
    def test_case_32(self): self.assertEqual(dict(tokenize_text('soft pink soft pink')[1]), {'soft': 2, 'pink': 2})
    def test_case_33(self): self.assertEqual(dict(tokenize_text('pinkish peachy reddish bluish')[1]), {'pinkish': 1, 'peachy': 1, 'reddish': 1, 'bluish': 1})
    def test_case_34(self): self.assertEqual(dict(tokenize_text('gorgeous clean and modern look')[1]), {'gorgeous': 1, 'clean': 1, 'and': 1, 'modern': 1, 'look': 1})
    def test_case_35(self): self.assertEqual(dict(tokenize_text('subtle, elegant, timeless, flawless')[1]), {'subtle': 1, ',': 3, 'elegant': 1, 'timeless': 1, 'flawless': 1})
    def test_case_36(self): self.assertEqual(dict(tokenize_text('not too shiny')[1]), {'not': 1, 'too': 1, 'shiny': 1})
    def test_case_37(self): self.assertEqual(dict(tokenize_text('no red, no pink, no orange')[1]), {'no': 3, 'red': 1, ',': 2, 'pink': 1, 'orange': 1})
    def test_case_38(self): self.assertEqual(dict(tokenize_text('Warm & cozy feel')[1]), {'warm': 1, '&': 1, 'cozy': 1, 'feel': 1})
    def test_case_39(self): self.assertEqual(dict(tokenize_text('sparkly-glam edgy rockstar')[1]), {'sparkly': 1, '-': 1, 'glam': 1, 'edgy': 1, 'rockstar': 1})
    def test_case_40(self): self.assertEqual(dict(tokenize_text('super intense makeup')[1]), {'super': 1, 'intense': 1, 'makeup': 1})
    def test_case_41(self): self.assertEqual(dict(tokenize_text('blush-toned skin')[1]), {'blush': 1, '-': 1, 'toned': 1, 'skin': 1})
    def test_case_42(self): self.assertEqual(dict(tokenize_text('crazy-colored eyeliner')[1]), {'crazy': 1, '-': 1, 'colored': 1, 'eyeliner': 1})
    def test_case_43(self): self.assertEqual(dict(tokenize_text('green. red. yellow. blue')[1]), {'green': 1, '.': 3, 'red': 1, 'yellow': 1, 'blue': 1})
    def test_case_44(self): self.assertEqual(dict(tokenize_text('wild yet clean')[1]), {'wild': 1, 'yet': 1, 'clean': 1})
    def test_case_45(self): self.assertEqual(dict(tokenize_text('I dislike overly glossy looks')[1]), {'i': 1, 'dislike': 1, 'overly': 1, 'glossy': 1, 'looks': 1})
    def test_case_46(self): self.assertEqual(dict(tokenize_text('extreme full glam or nothing')[1]), {'extreme': 1, 'full': 1, 'glam': 1, 'or': 1, 'nothing': 1})
    def test_case_47(self): self.assertEqual(dict(tokenize_text('shiny, glittery, sparkly things')[1]), {'shiny': 1, ',': 2, 'glittery': 1, 'sparkly': 1, 'things': 1})
    def test_case_48(self): self.assertEqual(dict(tokenize_text('a b a b a b')[1]), {'a': 3, 'b': 3})
    def test_case_49(self): self.assertEqual(dict(tokenize_text('blush? lipstick? gloss?')[1]), {'blush': 1, '?': 3, 'lipstick': 1, 'gloss': 1})
    def test_case_50(self): self.assertEqual(dict(tokenize_text('What about something glam, but less dramatic?')[1]), {'what': 1, 'about': 1, 'something': 1, 'glam': 1, ',': 1, 'but': 1, 'less': 1, 'dramatic': 1, '?': 1})
