# tests/extractors/general/utils/test_get_tokens_and_counts.py

import unittest
from Chatbot.extractors.general.utils.tokenizer import get_tokens_and_counts

class TestGetTokensAndCounts(unittest.TestCase):

    def run_case(self, text, expected):
        result = get_tokens_and_counts(text)
        self.assertEqual(expected, result)

    def test_case_01(self): self.run_case("blue", {"blue": 1})
    def test_case_02(self): self.run_case("Blue", {"blue": 1})
    def test_case_03(self): self.run_case("blue blue", {"blue": 2})
    def test_case_04(self): self.run_case("blue and pink", {"blue": 1, "and": 1, "pink": 1})
    def test_case_05(self): self.run_case("Soft pink and peachy tones", {"soft": 1, "pink": 1, "and": 1, "peachy": 1, "tones": 1})
    def test_case_06(self): self.run_case("Soft    pink   tones", {"soft": 1, "pink": 1, "tones": 1})
    def test_case_07(self): self.run_case("soft pink soft pink", {"soft": 2, "pink": 2})
    def test_case_08(self): self.run_case("soft  pink SOFT PINK", {"soft": 2, "pink": 2})
    def test_case_09(self): self.run_case("", {})
    def test_case_10(self): self.run_case("   ", {})
    def test_case_11(self): self.run_case("blue.", {"blue.": 1})
    def test_case_12(self): self.run_case("blue, pink", {"blue,": 1, "pink": 1})
    def test_case_13(self): self.run_case("blue-pink", {"blue-pink": 1})
    def test_case_14(self): self.run_case("Blue blue BLUE", {"blue": 3})
    def test_case_15(self): self.run_case("no-makeup makeup look", {"no-makeup": 1, "makeup": 1, "look": 1})
    def test_case_16(self): self.run_case("Subtle sparkle and glow", {"subtle": 1, "sparkle": 1, "and": 1, "glow": 1})
    def test_case_17(self): self.run_case("bold LOOK", {"bold": 1, "look": 1})
    def test_case_18(self): self.run_case("ROCK vibe ROCK VIBE", {"rock": 2, "vibe": 2})
    def test_case_19(self): self.run_case("nude tones nude", {"nude": 2, "tones": 1})
    def test_case_20(self): self.run_case("fresh and fresh and fresh", {"fresh": 3, "and": 2})
    def test_case_21(self): self.run_case("daily-glow", {"daily-glow": 1})
    def test_case_22(self): self.run_case("dewy look and feel", {"dewy": 1, "look": 1, "and": 1, "feel": 1})
    def test_case_23(self): self.run_case("soft pink. soft pink?", {"soft": 2, "pink.": 1, "pink?": 1})
    def test_case_24(self): self.run_case("natural natural natural", {"natural": 3})
    def test_case_25(self): self.run_case("soft_glam", {"soft_glam": 1})
    def test_case_26(self): self.run_case("glow    glow    glow", {"glow": 3})
    def test_case_27(self): self.run_case("matte matte matte", {"matte": 3})
    def test_case_28(self): self.run_case("matte-finish", {"matte-finish": 1})
    def test_case_29(self): self.run_case("classic red", {"classic": 1, "red": 1})
    def test_case_30(self): self.run_case("ultra soft", {"ultra": 1, "soft": 1})
    def test_case_31(self): self.run_case("bare skin bare skin", {"bare": 2, "skin": 2})
    def test_case_32(self): self.run_case("subtle subtle sparkle", {"subtle": 2, "sparkle": 1})
    def test_case_33(self): self.run_case("vintage glam", {"vintage": 1, "glam": 1})
    def test_case_34(self): self.run_case("clean clean clean", {"clean": 3})
    def test_case_35(self): self.run_case("fresh finish", {"fresh": 1, "finish": 1})
    def test_case_36(self): self.run_case("work appropriate", {"work": 1, "appropriate": 1})
    def test_case_37(self): self.run_case("peachy", {"peachy": 1})
    def test_case_38(self): self.run_case("taupey beige taupey beige", {"taupey": 2, "beige": 2})
    def test_case_39(self): self.run_case("charcoal charcoal", {"charcoal": 2})
    def test_case_40(self): self.run_case("rose rose gold", {"rose": 2, "gold": 1})
    def test_case_41(self): self.run_case("rosé rosé", {"rosé": 2})
    def test_case_42(self): self.run_case("copper glow", {"copper": 1, "glow": 1})
    def test_case_43(self): self.run_case("bold red lips", {"bold": 1, "red": 1, "lips": 1})
    def test_case_44(self): self.run_case("neutral matte", {"neutral": 1, "matte": 1})
    def test_case_45(self): self.run_case("radiant radiant skin", {"radiant": 2, "skin": 1})
    def test_case_46(self): self.run_case("soft cool pink", {"soft": 1, "cool": 1, "pink": 1})
    def test_case_47(self): self.run_case("elegant", {"elegant": 1})
    def test_case_48(self): self.run_case("soft-glam", {"soft-glam": 1})
    def test_case_49(self): self.run_case("classic classic classic red", {"classic": 3, "red": 1})
    def test_case_50(self): self.run_case("moody glam", {"moody": 1, "glam": 1})
