# tests/extractors/general/utils/test_match_expression_aliases.py

import unittest
from Chatbot.extractors.general.utils.fuzzy_match import match_expression_aliases

class TestMatchExpressionAliases(unittest.TestCase):

    def run_case(self, input_text, aliases, expected):
        result = match_expression_aliases(input_text, aliases)
        print(f"Expected: {expected} | Actual: {result}")
        self.assertEqual(expected, result)

    def test_case_01(self): self.run_case("soft glam", ["soft glam"], True)
    def test_case_02(self): self.run_case("Soft Glam", ["soft glam"], True)
    def test_case_03(self): self.run_case("I love soft glam", ["soft glam"], True)
    def test_case_04(self): self.run_case("glam soft", ["soft glam"], True)
    def test_case_05(self): self.run_case("subtle sparkle", ["subtle sparkle"], True)
    def test_case_06(self): self.run_case("subtle sparkl", ["subtle sparkle"], True)
    def test_case_07(self): self.run_case("romantik", ["romantic"], True)
    def test_case_08(self): self.run_case("romantic", ["romantic"], True)
    def test_case_09(self): self.run_case("valentine date", ["valentine"], True)
    def test_case_10(self): self.run_case("valentines", ["valentine"], True)
    def test_case_11(self): self.run_case("valentine night", ["romantic"], False)
    def test_case_12(self): self.run_case("red carpet", ["glamorous"], False)
    def test_case_13(self): self.run_case("redcarpet", ["red carpet"], True)
    def test_case_14(self): self.run_case("natural", ["natural"], True)
    def test_case_15(self): self.run_case("no makeup", ["natural"], False)
    def test_case_16(self): self.run_case("bare skin", ["bare skin"], True)
    def test_case_17(self): self.run_case("baree skin", ["bare skin"], True)
    def test_case_18(self): self.run_case("rock vibe", ["edgy"], False)
    def test_case_19(self): self.run_case("rockvibe", ["rock vibe"], True)
    def test_case_20(self): self.run_case("bold look", ["bold"], True)
    def test_case_21(self): self.run_case("bold looook", ["bold"], True)
    def test_case_22(self): self.run_case("glowy", ["soft glam"], False)
    def test_case_23(self): self.run_case("clean elegant", ["elegant"], True)
    def test_case_24(self): self.run_case("clean and elegant", ["elegant"], True)
    def test_case_25(self): self.run_case("clean and classy", ["elegant"], False)
    def test_case_26(self): self.run_case("hollywood", ["glamorous"], False)
    def test_case_27(self): self.run_case("glamourous", ["glamorous"], True)
    def test_case_28(self): self.run_case("fresh and clean", ["fresh"], True)
    def test_case_29(self): self.run_case("fresh clean", ["fresh"], True)
    def test_case_30(self): self.run_case("edgy look", ["edgy"], True)
    def test_case_31(self): self.run_case("edge", ["edgy"], False)
    def test_case_32(self): self.run_case("bold and edgy", ["bold"], True)
    def test_case_33(self): self.run_case("no makeup", ["no makeup"], True)
    def test_case_34(self): self.run_case("nomakeup", ["no makeup"], True)
    def test_case_35(self): self.run_case("natural finish", ["natural"], True)
    def test_case_36(self): self.run_case("softglam", ["soft glam"], True)
    def test_case_37(self): self.run_case("soft glam glow", ["soft glam"], True)
    def test_case_38(self): self.run_case("edgy sparkle", ["soft glam"], False)
    def test_case_39(self): self.run_case("barely there", ["bare skin"], False)
    def test_case_40(self): self.run_case("glamorous", ["glamorous"], True)
    def test_case_41(self): self.run_case("elegant", ["elegant"], True)
    def test_case_42(self): self.run_case("romantic", ["romantic"], True)
    def test_case_43(self): self.run_case("valentine", ["romantic"], False)
    def test_case_44(self): self.run_case("bold edge", ["edgy"], False)
    def test_case_45(self): self.run_case("barely there glam", ["bare skin"], False)
    def test_case_46(self): self.run_case("minimal makeup", ["minimal"], True)
    def test_case_47(self): self.run_case("minmal", ["minimal"], True)
    def test_case_48(self): self.run_case("vibrnt", ["vibrant"], True)
    def test_case_49(self): self.run_case("trendii", ["trendy"], True)
    def test_case_50(self): self.run_case("fun playful look", ["playful"], True)
