# tests/extractors/general/utils/test_normalize_token.py

import unittest
from Chatbot.extractors.color.utils.token_utils import normalize_token

class TestNormalizeToken(unittest.TestCase):

    def run_case(self, token, expected):
        result = normalize_token(token)
        print(f"Expected: {expected} | Actual: {result}")
        self.assertEqual(expected, result)

    def test_case_01(self): self.run_case("blue", "blue")
    def test_case_02(self): self.run_case(" Blue", "blue")
    def test_case_03(self): self.run_case("blue ", "blue")
    def test_case_04(self): self.run_case("  blue  ", "blue")
    def test_case_05(self): self.run_case("BLUE", "blue")
    def test_case_06(self): self.run_case("BlUe", "blue")
    def test_case_07(self): self.run_case("\tbluE", "blue")
    def test_case_08(self): self.run_case("blue\n", "blue")
    def test_case_09(self): self.run_case(" blue\t\n", "blue")
    def test_case_10(self): self.run_case(" light-blue ", "light-blue")
    def test_case_11(self): self.run_case("  soft glam", "soft glam")
    def test_case_12(self): self.run_case("Soft Glam  ", "soft glam")
    def test_case_13(self): self.run_case("  Soft Glam  ", "soft glam")
    def test_case_14(self): self.run_case("SoftGlam", "softglam")
    def test_case_15(self): self.run_case("rose_gold", "rose_gold")
    def test_case_16(self): self.run_case("rose gold ", "rose gold")
    def test_case_17(self): self.run_case("   rose   gold   ", "rose   gold")
    def test_case_18(self): self.run_case("GOLD", "gold")
    def test_case_19(self): self.run_case("gold", "gold")
    def test_case_20(self): self.run_case("nude", "nude")
    def test_case_21(self): self.run_case("  nude", "nude")
    def test_case_22(self): self.run_case("Nude", "nude")
    def test_case_23(self): self.run_case("nUdE", "nude")
    def test_case_24(self): self.run_case("    ", "")
    def test_case_25(self): self.run_case("\n\t  ", "")
    def test_case_26(self): self.run_case("", "")
    def test_case_27(self): self.run_case("cream", "cream")
    def test_case_28(self): self.run_case("cream  ", "cream")
    def test_case_29(self): self.run_case(" creamy ", "creamy")
    def test_case_30(self): self.run_case(" CREAMY", "creamy")
    def test_case_31(self): self.run_case("creamY", "creamy")
    def test_case_32(self): self.run_case("lavender-blush", "lavender-blush")
    def test_case_33(self): self.run_case("  lavender blush  ", "lavender blush")
    def test_case_34(self): self.run_case("glowy", "glowy")
    def test_case_35(self): self.run_case("GlOwY", "glowy")
    def test_case_36(self): self.run_case("off white", "off white")
    def test_case_37(self): self.run_case("  Off White ", "off white")
    def test_case_38(self): self.run_case("soft  glam", "soft  glam")  # double space is preserved
    def test_case_39(self): self.run_case("bold look", "bold look")
    def test_case_40(self): self.run_case("Bold Look", "bold look")
    def test_case_41(self): self.run_case("bare  skin", "bare  skin")
    def test_case_42(self): self.run_case("bare skin", "bare skin")
    def test_case_43(self): self.run_case("valentine", "valentine")
    def test_case_44(self): self.run_case("Valentine", "valentine")
    def test_case_45(self): self.run_case("VALENTINE", "valentine")
    def test_case_46(self): self.run_case("soft-glam", "soft-glam")
    def test_case_47(self): self.run_case("subtle sparkle", "subtle sparkle")
    def test_case_48(self): self.run_case("subtle  sparkle", "subtle  sparkle")
    def test_case_49(self): self.run_case("subtle-sparkle", "subtle-sparkle")
    def test_case_50(self): self.run_case("natural", "natural")
