import unittest
from Chatbot.extractors.color.extraction.standalone import _finalize_standalone_phrases

class TestFinalizeStandalonePhrases(unittest.TestCase):

    def run_case(self, injected, filtered, expected, debug=False):
        result = _finalize_standalone_phrases(set(injected), set(filtered), debug)
        print(f"Expected: {expected}")
        print(f"Actual  : {result}")
        self.assertEqual(set(expected), result)

    def test_case_01(self): self.run_case([], [], [])
    def test_case_02(self): self.run_case(["soft"], [], ["soft"])
    def test_case_03(self): self.run_case([], ["pink"], ["pink"])
    def test_case_04(self): self.run_case(["soft"], ["pink"], ["soft", "pink"])
    def test_case_05(self): self.run_case(["soft"], ["soft"], ["soft"])
    def test_case_06(self): self.run_case(["soft", "muted"], [], ["soft", "muted"])
    def test_case_07(self): self.run_case([], ["beige", "coral"], ["beige", "coral"])
    def test_case_08(self): self.run_case(["warm"], ["cool"], ["warm", "cool"])
    def test_case_09(self): self.run_case(["cool"], ["cool"], ["cool"])
    def test_case_10(self): self.run_case(["warm"], ["warm", "cool"], ["warm", "cool"])
    def test_case_11(self): self.run_case(["a"], ["b"], ["a", "b"])
    def test_case_12(self): self.run_case(["a", "b"], ["c", "d"], ["a", "b", "c", "d"])
    def test_case_13(self): self.run_case(["a", "b", "c"], ["c", "d"], ["a", "b", "c", "d"])
    def test_case_14(self): self.run_case(["a", "b"], ["a", "b", "c"], ["a", "b", "c"])
    def test_case_15(self): self.run_case(["a"], ["a"], ["a"])
    def test_case_16(self): self.run_case(["rose", "rosy"], ["rosy"], ["rose", "rosy"])
    def test_case_17(self): self.run_case(["muted"], ["muted", "strong"], ["muted", "strong"])
    def test_case_18(self): self.run_case(["soft", "warm"], ["peach", "warm"], ["soft", "warm", "peach"])
    def test_case_19(self): self.run_case(["tone1"], ["tone2"], ["tone1", "tone2"])
    def test_case_20(self): self.run_case(["A"], ["a"], ["A", "a"])
    def test_case_21(self): self.run_case(["a", "b", "c"], ["d", "e", "f"], ["a", "b", "c", "d", "e", "f"])
    def test_case_22(self): self.run_case(["a", "b"], ["c", "d", "e", "f"], ["a", "b", "c", "d", "e", "f"])
    def test_case_23(self): self.run_case(["deep"], ["nude", "deep"], ["deep", "nude"])
    def test_case_24(self): self.run_case(["rosy", "bare"], ["rosy", "bare"], ["rosy", "bare"])
    def test_case_25(self): self.run_case(["x"], ["y", "z"], ["x", "y", "z"])
    def test_case_26(self): self.run_case(["x", "y", "z"], ["z"], ["x", "y", "z"])
    def test_case_27(self): self.run_case(["rosy", "cool"], ["rosy", "warm"], ["rosy", "cool", "warm"])
    def test_case_28(self): self.run_case(["muted"], ["muted"], ["muted"])
    def test_case_29(self): self.run_case(["ultra"], ["light", "ultra"], ["ultra", "light"])
    def test_case_30(self): self.run_case(["tone"], ["tone", "shade"], ["tone", "shade"])
    def test_case_31(self): self.run_case(["light", "shade"], ["shade"], ["light", "shade"])
    def test_case_32(self): self.run_case(["blush"], ["pink", "blush"], ["blush", "pink"])
    def test_case_33(self): self.run_case(["cool"], ["neutral", "cool"], ["neutral", "cool"])
    def test_case_34(self): self.run_case(["icy", "warm"], ["icy", "cool"], ["icy", "warm", "cool"])
    def test_case_35(self): self.run_case(["dust"], ["dusty"], ["dust", "dusty"])
    def test_case_36(self): self.run_case(["muted"], ["peach", "peachy"], ["muted", "peach", "peachy"])
    def test_case_37(self): self.run_case(["vivid", "subtle"], ["bold", "vivid"], ["vivid", "subtle", "bold"])
    def test_case_38(self): self.run_case(["a", "b", "c"], ["c", "d", "e", "f"], ["a", "b", "c", "d", "e", "f"])
    def test_case_39(self): self.run_case(["light", "night"], ["romantic", "dramatic"], ["light", "night", "romantic", "dramatic"])
    def test_case_40(self): self.run_case(["icy", "icy"], ["icy"], ["icy"])
    def test_case_41(self): self.run_case(["moody"], ["deep", "moody"], ["moody", "deep"])
    def test_case_42(self): self.run_case(["blush"], ["blush", "flush"], ["blush", "flush"])
    def test_case_43(self): self.run_case(["soft", "glam"], ["soft glam"], ["soft", "glam", "soft glam"])
    def test_case_44(self): self.run_case(["neutral", "base"], ["neutral"], ["neutral", "base"])
    def test_case_45(self): self.run_case(["pale"], ["pale", "bold", "subtle"], ["pale", "bold", "subtle"])
    def test_case_46(self): self.run_case(["clean", "natural"], ["clean"], ["clean", "natural"])
    def test_case_47(self): self.run_case(["shade", "light"], ["shade"], ["shade", "light"])
    def test_case_48(self): self.run_case(["warm"], ["warm", "warm", "warm"], ["warm"])
    def test_case_49(self): self.run_case(["rosy", "rosy", "rosy"], ["rosy"], ["rosy"])
    def test_case_50(self): self.run_case(["x", "y", "z"], ["x", "y", "z", "w"], ["x", "y", "z", "w"])

if __name__ == "__main__":
    unittest.main()
