# tests/extractors/color/test_fuzzy_match_rgb_from_known_colors.py

import unittest
from Chatbot.extractors.color.utils.rgb_distance import fuzzy_match_rgb_from_known_colors

class TestFuzzyMatchRgbFromKnownColors(unittest.TestCase):

    def test_case_01(self): self.assertEqual((255, 255, 255), fuzzy_match_rgb_from_known_colors("white"))
    def test_case_02(self): self.assertEqual((0, 0, 0), fuzzy_match_rgb_from_known_colors("black"))
    def test_case_03(self): self.assertEqual((255, 0, 0), fuzzy_match_rgb_from_known_colors("red"))
    def test_case_04(self): self.assertEqual((0, 0, 255), fuzzy_match_rgb_from_known_colors("blue"))
    def test_case_05(self): self.assertEqual((0, 128, 0), fuzzy_match_rgb_from_known_colors("green"))
    def test_case_06(self): self.assertEqual((255, 255, 0), fuzzy_match_rgb_from_known_colors("yellow"))
    def test_case_07(self): self.assertEqual((255, 165, 0), fuzzy_match_rgb_from_known_colors("orange"))
    def test_case_08(self): self.assertEqual((128, 0, 128), fuzzy_match_rgb_from_known_colors("purple"))
    def test_case_09(self): self.assertEqual((255, 192, 203), fuzzy_match_rgb_from_known_colors("pink"))
    def test_case_10(self): self.assertEqual((128, 128, 128), fuzzy_match_rgb_from_known_colors("gray"))

    def test_case_11(self): self.assertEqual((165, 42, 42), fuzzy_match_rgb_from_known_colors("brown"))
    def test_case_12(self): self.assertEqual((135, 206, 235), fuzzy_match_rgb_from_known_colors("sky blue"))
    def test_case_13(self): self.assertEqual((250, 128, 114), fuzzy_match_rgb_from_known_colors("salmon"))
    def test_case_14(self): self.assertEqual((255, 228, 225), fuzzy_match_rgb_from_known_colors("misty rose"))
    def test_case_15(self): self.assertEqual((245, 245, 220), fuzzy_match_rgb_from_known_colors("beige"))
    def test_case_16(self): self.assertEqual((70, 130, 180), fuzzy_match_rgb_from_known_colors("steel blue"))
    def test_case_17(self): self.assertEqual((255, 99, 71), fuzzy_match_rgb_from_known_colors("tomato"))
    def test_case_18(self): self.assertEqual((176, 224, 230), fuzzy_match_rgb_from_known_colors("powder blue"))
    def test_case_19(self): self.assertEqual((240, 248, 255), fuzzy_match_rgb_from_known_colors("alice blue"))
    def test_case_20(self): self.assertEqual((250, 235, 215), fuzzy_match_rgb_from_known_colors("antique white"))

    def test_case_21(self): self.assertEqual((152, 251, 152), fuzzy_match_rgb_from_known_colors("pale green"))
    def test_case_22(self): self.assertEqual((238, 130, 238), fuzzy_match_rgb_from_known_colors("violet"))
    def test_case_23(self): self.assertEqual((186, 85, 211), fuzzy_match_rgb_from_known_colors("medium orchid"))
    def test_case_24(self): self.assertEqual((255, 160, 122), fuzzy_match_rgb_from_known_colors("light salmon"))
    def test_case_25(self): self.assertEqual((255, 105, 180), fuzzy_match_rgb_from_known_colors("hot pink"))
    def test_case_26(self): self.assertEqual((173, 216, 230), fuzzy_match_rgb_from_known_colors("light blue"))
    def test_case_27(self): self.assertEqual((0, 206, 209), fuzzy_match_rgb_from_known_colors("dark turquoise"))
    def test_case_28(self): self.assertEqual((154, 205, 50), fuzzy_match_rgb_from_known_colors("yellow green"))
    def test_case_29(self): self.assertEqual((255, 20, 147), fuzzy_match_rgb_from_known_colors("deep pink"))
    def test_case_30(self): self.assertEqual((46, 139, 87), fuzzy_match_rgb_from_known_colors("sea green"))

    def test_case_31(self): self.assertEqual((255, 215, 0), fuzzy_match_rgb_from_known_colors("gold"))
    def test_case_32(self): self.assertEqual((255, 182, 193), fuzzy_match_rgb_from_known_colors("light pink"))
    def test_case_33(self): self.assertEqual((72, 61, 139), fuzzy_match_rgb_from_known_colors("dark slate blue"))
    def test_case_34(self): self.assertEqual((105, 105, 105), fuzzy_match_rgb_from_known_colors("dim gray"))
    def test_case_35(self): self.assertEqual((255, 248, 220), fuzzy_match_rgb_from_known_colors("cornsilk"))
    def test_case_36(self): self.assertEqual((107, 142, 35), fuzzy_match_rgb_from_known_colors("olive drab"))
    def test_case_37(self): self.assertEqual((233, 150, 122), fuzzy_match_rgb_from_known_colors("dark salmon"))
    def test_case_38(self): self.assertEqual((189, 183, 107), fuzzy_match_rgb_from_known_colors("dark khaki"))
    def test_case_39(self): self.assertEqual((47, 79, 79), fuzzy_match_rgb_from_known_colors("dark slate gray"))
    def test_case_40(self): self.assertEqual((255, 245, 238), fuzzy_match_rgb_from_known_colors("seashell"))

    def test_case_41(self): self.assertEqual((255, 250, 250), fuzzy_match_rgb_from_known_colors("snow"))
    def test_case_42(self): self.assertEqual((0, 191, 255), fuzzy_match_rgb_from_known_colors("deep sky blue"))
    def test_case_43(self): self.assertEqual((0, 255, 255), fuzzy_match_rgb_from_known_colors("cyan"))
    def test_case_44(self): self.assertEqual((221, 160, 221), fuzzy_match_rgb_from_known_colors("plum"))
    def test_case_45(self): self.assertEqual((255, 127, 80), fuzzy_match_rgb_from_known_colors("coral"))
    def test_case_46(self): self.assertEqual((218, 112, 214), fuzzy_match_rgb_from_known_colors("orchid"))
    def test_case_47(self): self.assertEqual((250, 250, 210), fuzzy_match_rgb_from_known_colors("light goldenrod yellow"))
    def test_case_48(self): self.assertEqual((100, 149, 237), fuzzy_match_rgb_from_known_colors("cornflower blue"))
    def test_case_49(self): self.assertEqual((240, 230, 140), fuzzy_match_rgb_from_known_colors("khaki"))
    def test_case_50(self): self.assertEqual((128, 0, 0), fuzzy_match_rgb_from_known_colors("maroon"))
